### ISSUE TITLE
Fail to run the command `azd up`

### ISSUE THREAD

**Issue by jerryshia** [microsoft/aoai-logging-with-apim#10]
**Describe the issue:**
In [Readme](https://github.com/microsoft/aoai-logging-with-apim?tab=readme-ov-file#how-to-deploy-the-solution), fail to run the command `azd up`  and there is an error: "failed deploying service 'logParserFunction'".

![image](https://github.com/microsoft/aoai-logging-with-apim/assets/139106314/a8a7308c-5ccd-4a3e-9798-feef961d4561)

**Repro Steps:**
1.Run `azd up`
2.Select an Azure subscription and enter the environment name.

**Expected behavior:**
Successfully deployed the solution.

@kenakamu and @hemarina for notification

**Comment by kenakamu** [comment]
Thanks for the report. Could you let me know which region you selected and environment name you use?

**Comment by jerryshia** [comment]
@kenakamu The region I have chosen is `Sweden Central`, and the environment name I have used is `sjlaoai`.

**Comment by kenakamu** [comment]
I couldn't repro the issue by using sjlaoai1 and 2 in Sweden Central. As the function name is different from your environment name convention, did you specify additional parameters?

![image](https://github.com/microsoft/aoai-logging-with-apim/assets/9940668/b378bf91-b087-45dd-9fa5-050aa3366c12)

**Comment by v-xuto** [comment]
@kenakamu We are re-verifying and will update here when the results are available.

**Comment by zedy-wj** [comment]
Hi, @kenakamu - We have stably reproduced this error in multiple tests. 

> did you specify additional parameters?

We only selected `subscription` and `location`, and did not modify other parameters.

First this error is:
```
Post "https://func-logparser-zedy03.scm.azurewebsites.net/api/zipdeploy?isAsync=true": dial tcp: lookup func-logparser-zedy03.scm.azurewebsites.net: no such host
```

There is a slight difference from the actual function url:
```
https://func-logparser-zedy03.azurewebsites.net
```


Secondly, when we click on the url link, we get a prompt: This website cannot be accessed. We guess whether we lost some permissions during the DNS transfer?

**Comment by kenakamu** [comment]
The URL is to manage the app (scm), not the actual app URL which is the expected behavior. 
Maybe the default firewall setting didn't respect the bicep. Could you check the network setting for both the function and the web app to see if it allows external access? If not, could you change it to external access and azd deploy to just deploy the application to test if the deploy succeeds or not? It's a bit difficult for me to debug as I cannot repro the issue by some reason...

**Comment by zedy-wj** [comment]
@kenakamu - We can run `azd up` successfully after disconnecting the `VPN`, but we cannot open the loggingwebapi endpoint normally. 
Error Message: 

![image](https://github.com/microsoft/aoai-logging-with-apim/assets/81678720/e58aacf5-d1a1-4460-9b2c-a087ec35030a)


What should the expected actual page look like? Do we need any additional operations?

**Comment by kenakamu** [comment]
@zedy-wj Thanks for confirming! This solution logs the AOAI usage, so the Web API is not meant to display anything. If you call the APIM endpoint by any tool such as Postman, Semantic Kernel, Langchain, then you can see the log in Application Insights.

**Comment by kenakamu** [comment]
@zedy-wj any update on this?

**Comment by zedy-wj** [comment]
@kenakamu - We triggered the function by updating the cosmos DB as described in the Readme, after which we saw logs, thank you for your help, we will close this issue.

![image](https://github.com/microsoft/aoai-logging-with-apim/assets/81678720/0da66d03-1015-41ed-b740-03d64564a0f5)

**Comment by v-xuto** [comment]
@hemarina Regarding this issue, this template can be deployed successfully only if the VPN is disconnected. Is this allowed?

**Comment by kenakamu** [comment]
@zedy-wj The final log will be stored in the Application Insights, so you don't need to see the cosmos db directly.

**Comment by zedy-wj** [comment]
@kenakamu - We are looking at logs in Application Insights. But we need to trigger the function first.

However, currently the function is triggered by the `Cosmos DB change feed` (as described in this [README](https://github.com/microsoft/aoai-logging-with-apim/tree/main/LoggingWebApi#how-to-run-in-local-environment)), and in the process we need to manually configure additional permission about network.

**Comment by kenakamu** [comment]
Thanks for confirming it.  I am closing this for now.
